services:
  - type: web
    name: mdcrx-services
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
    autoDeploy: true

